FROM ubuntu:18.04
WORKDIR /hytao
COPY ./src_code ./
RUN apt-get update -y && \
    apt-get install -y python3.8 python3-pip python3.8-dev iputils-ping
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt
